apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: complete
  name: complete-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: complete
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: complete
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: 0.9
            memory: 256Mi
          requests:
            cpu: 0.5
            memory: 64Mi
      #  volumeMounts:
      #  - name: html
      #    mountPath: /usr/share/nginx/html
        startupProbe:
          tcpSocket: 
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:80/
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5
      volumes:
      - name: html
        emptyDir: 
          sizeLimit: 256Mi
        

