apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: meu-service-monitor
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
  - port: http
    interval: 30s
