apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-https
  name: nginx-https
spec:
  containers:
  - image: nginx
    name: nginx-https
    ports:
    - containerPort: 80
    - containerPort: 443
    volumeMounts:
    - mountPath: /etc/nginx/nginx.conf
      name: nginx-conf-volume
      subPath: nginx.conf
    - mountPath: /etc/nginx/tls
      name: nginx-tls
  volumes:
   - name: nginx-conf-volume
     configmap:
       name: nginx-config
   - name: nginx-tls
     secret:
       secretName: nginx-secret
       items:
       - key: tls.key
         path: nginx.key
       - key: tls.crt
         path: nginx.crt