apiVersion: v1
data:
  nginx.conf: "events { }\r\nhttp {\r\n    server {\r\n        listen 80;\r\n        listen
    443 ssl;\r\n        ssl_certificate /etc/nginx/tls/nginx.crt;\r\n        ssl_certificate_key
    /etc/nginx/tls/nginx.key;\r\n\r\n        location / {\r\n          return
    200 'Olá terráqueos!\\n';\r\n          add_header Content-Type text/plain;\r\n
    \         }\r\n    }\r\n}"
kind: ConfigMap
metadata:
  name: nginx-config
