apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJmaWxpcGV6IiwicGFzc3dvcmQiOiJ3aW5kb3dzMTEiLCJlbWFpbCI6ImZpbGlwZXptYXJyb25AaG90bWFpbC5jb20iLCJhdXRoIjoiWm1sc2FYQmxlanAzYVc1a2IzZHpNVEU9In19fQ==
kind: Secret
metadata:
  name: dockerhub-credentials
type: kubernetes.io/dockerconfigjson
