apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-configmap-pod
  name: nginx-configmap-pod
spec:
  containers:
  - image: nginx
    name: nginx-configmap-container
    ports:
    - containerPort: 80
    - containerPort: 443
    volumeMounts:
    - mountPath: /etc/nginx/nginx.conf
      name: nginx-configmap-volume
      subPath: nginx.conf
    - mountPath: /etc/nginx/tls
      name: nginx-tls
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 64Mi
  volumes:
  - name: nginx-configmap-volume
    configMap:
      name: nginx-config
  - name: nginx-tls
    secret:
      secretName: tls
      items:
      - key: tls.key
        path: chave-privada.key
      - key: tls.crt
        path: certificado.crt
 